---
- name: create src directory
  file: path={{ src_dir }}/supervisor.local state=directory owner=root group=root

- name: copy resources to the src directory
  copy: src=common/files/get-pip.py dest={{ src_dir }}/supervisor.local owner=root group=root
        backup=yes

- name: install pip
  command: python {{ src_dir }}/supervisor.local/get-pip.py creates=/usr/bin/pip

- name: install supervisor
  pip: name={{ item.name }} version={{ item.version }} extra_args="-M"
  with_items:
    - { name: supervisor, version: "{{ supervisor_version }}" }

- name: copy supervisord.conf
  copy: src=supervisord.conf dest=/etc/ mode=0744 owner=root group=root
        backup=yes
  notify: restart supervisord

- name: copy supervisord init script
  copy: src=supervisord dest=/etc/init.d/ mode=0754 owner=root group=root
        backup=yes
  notify: restart supervisord

- name: create supervisord directories
  file: path={{ item }} state=directory owner=root group=root
  with_items:
    - /etc/supervisord.d
    - /var/run/supervisord
    - /var/log/supervisord

- name: copy supervisord user custom script
  copy: src={{ item }} dest=/etc/supervisord.d/ mode=0754 owner=root group=root
  notify: restart supervisord
  with_fileglob: /canvases/{{ canvas_id }}/etc/supervisor/custom-*.ini

- name: start supervisord
  service: name=supervisord state=started enabled=yes
