---
- hosts: app
  sudo: yes
  roles:
    - { role: opt.local }
    - { role: db.mysql.shared, client_only: yes }
    - { role: disk.shared, app_type: python }
    - role: daemon.django.gunicorn
  vars_files:
    - "{{ local_ansible_resources_dir }}/vars/interpreter.python.yml"
