---
- hosts: app
  sudo: yes
  roles:
    - role: interpreter.ruby
    - { role: disk.shared, app_type: ruby }
    - role: daemon.ruby.unicorn
  vars_files:
    - "{{ local_ansible_resources_dir }}/vars/interpreter.ruby.yml"
