---
app_user: "{{ nginx_user }}"
app_group: "{{ nginx_group }}"

nginx_vars: {
  server_socket: "{{ web_port if web_port is defined else 80 }}",
  http_port: "{{ http_port if http_port is defined else 80 }}",
  https_port: "{{ https_port if https_port is defined else 443 }}",
  server_name: "{{ server_name if server_name is defined else ansible_eth0.ipv4.address }}",
  server_addr: "$server_addr",
  document_root_prefix: "/canvases/{{ canvas_id }}",
}
