---
- name: update supervisorctl
  command: supervisorctl update

- name: restart php-fpm
  supervisorctl: name=php-fpm({{ canvas_id }}) state=restarted

- name: reload php-fpm
  command: supervisorctl pid "php-fpm({{ canvas_id }})" | xargs kill -s USR2
