---
- name: create canvas application script directory
  file: path={{ canvas_scripts_dir }} state=directory

- name: set environment script
  template: src=common/templates/app_envs.sh.j2 dest={{ canvas_scripts_dir }}/envs.sh mode=754
            backup=yes

- name: check custom environment template exists
  local_action: file path={{ local_ansible_resources_dir }}/custom_envs.j2 state=file
  sudo: no
  register: custom_env_exists
  ignore_errors: yes

- name: set custom environment script
  template: src={{ local_ansible_resources_dir }}/custom_envs.j2
            dest={{ canvas_scripts_dir }}/custom_envs.sh mode=754
            backup=yes
  when: custom_env_exists|success

- name: create blank custom environment script
  copy: dest={{ canvas_scripts_dir }}/custom_envs.sh content="" mode=754
        backup=yes
  when: custom_env_exists|failed

- name: check custom environment ini template exists
  local_action: file path={{ local_ansible_resources_dir }}/server_variables.j2 state=file
  sudo: no
  register: custom_env_ini_exists
  ignore_errors: yes
